PROGRAM Median;

PROCEDURE Median (a, b, c : INTEGER, VAR OUTPUT : INTEGER);
VAR
    NUMBERS_IN_ARRAY : ARRAY [1..3] OF INTEGER;
BEGIN
    NUMBERS_IN_ARRAY := [a, b, c];
    WriteLn(NUMBERS_IN_ARRAY)
END;

VAR
    OUTPUT : INTEGER;
BEGIN
    WriteLn('3, 5, 7');
    Median(3, 5, 7, OUTPUT);
END.