PROGRAM MedianCalc;

PROCEDURE Median (a, b, c : INTEGER; VAR OUTPUT : INTEGER);
VAR
    NUMBERS_IN_ARRAY : ARRAY [1..3] OF INTEGER;
    ORDERED_ARRAY: ARRAY [1..2] OF INTEGER;
    i : INTEGER;
BEGIN
    NUMBERS_IN_ARRAY[1] := a;
    NUMBERS_IN_ARRAY[2] := b;
    NUMBERS_IN_ARRAY[3] := c;

    ORDERED_ARRAY[1] := NUMBERS_IN_ARRAY[1]
    ORDERED_ARRAY[3] := NUMBERS_IN_ARRAY[1]

    FOR i := 2 TO 3 DO BEGIN
        IF ORDERED_ARRAY[1] < NUMBERS_IN_ARRAY[i] THEN ORDERED_ARRAY[1] := NUMBERS_IN_ARRAY[i]
    END;

    FOR i := 2 TO 3 DO BEGIN
        IF ORDERED_ARRAY[1] < NUMBERS_IN_ARRAY[i] THEN ORDERED_ARRAY[1] := NUMBERS_IN_ARRAY[i]
    END;



    WriteLn(NUMBERS_IN_ARRAY[1]);
END;

VAR
    OUTPUT : INTEGER;
BEGIN
    WriteLn('3, 5, 7');
    Median(3, 5, 7, OUTPUT);
END.